In [1]:
# Import pandas library
import pandas as pd

In [2]:
# Read the state_baby_names dataset
state_babies = pd.read_csv(
    r'D:\MiniForge\Ex_Files_Intro_to_Data_Science\Ex_Files_Intro_to_Data_Science\Exercise Files\state_baby_names.csv'
)

In [3]:
# Display first 5 rows
state_babies.head()

   Id      Name  Year Gender State  Count
0   1      Mary  1910      F    AK     14
1   2     Annie  1910      F    AK     12
2   3      Anna  1910      F    AK     10
3   4  Margaret  1910      F    AK      8
4   5     Helen  1910      F    AK      7

In [4]:
# Create a new DataFrame containing only rows from the year 2014
state_babies_2014 = state_babies.loc[state_babies['Year'] == 2014, :]

In [5]:
# Display the filtered 2014 dataset
state_babies_2014

              Id      Name  Year Gender State  Count
13522      13523      Emma  2014      F    AK     50
13523      13524    Olivia  2014      F    AK     47
13524      13525    Sophia  2014      F    AK     43
13525      13526    Aurora  2014      F    AK     35
13526      13527  Isabella  2014      F    AK     33
...          ...       ...   ...    ...   ...    ...
5647421  5647422      Seth  2014      M    WY      5
5647422  5647423   Spencer  2014      M    WY      5
5647423  5647424      Tyce  2014      M    WY      5
5647424  5647425    Victor  2014      M    WY      5
5647425  5647426    Waylon  2014      M    WY      5

[94148 rows x 6 columns]

In [6]:
# Create a new DataFrame containing only California rows from 2014
ca_babies_2014 = state_babies_2014.loc[state_babies_2014['State'] == 'CA', :]

In [7]:
# Display California baby names from 2014
ca_babies_2014

            Id      Name  Year Gender State  Count
561495  561496    Sophia  2014      F    CA   3162
561496  561497  Isabella  2014      F    CA   2705
561497  561498      Emma  2014      F    CA   2662
561498  561499       Mia  2014      F    CA   2627
561499  561500    Olivia  2014      F    CA   2407
...        ...       ...   ...    ...   ...    ...
710225  710226    Zakary  2014      M    CA      5
710226  710227   Zealand  2014      M    CA      5
710227  710228      Ziad  2014      M    CA      5
710228  710229    Zidane  2014      M    CA      5
710229  710230     Ziyad  2014      M    CA      5

[6903 rows x 6 columns]

In [8]:
# Sort the California 2014 baby names by Count from highest to lowest
sorted_ca_2014 = ca_babies_2014.sort_values("Count", ascending=False)

In [12]:
# Display the sorted California 2014 dataset
sorted_ca_2014

            Id      Name  Year Gender State  Count
561495  561496    Sophia  2014      F    CA   3162
707311  707312      Noah  2014      M    CA   2761
561496  561497  Isabella  2014      F    CA   2705
707312  707313     Jacob  2014      M    CA   2692
561497  561498      Emma  2014      F    CA   2662
...        ...       ...   ...    ...   ...    ...
710215  710216    Yamato  2014      M    CA      5
710214  710215     Xaden  2014      M    CA      5
710213  710214      Xabi  2014      M    CA      5
710212  710213      Wren  2014      M    CA      5
710211  710212    Westyn  2014      M    CA      5

[6903 rows x 6 columns]

In [13]:
# Display the first row from the sorted California 2014 dataset
sorted_ca_2014.iloc[0]

Id        561496
Name      Sophia
Year        2014
Gender         F
State         CA
Count       3162
Name: 561495, dtype: object

In [14]:
# Display the first row from the sorted California 2014 dataset
sorted_ca_2014.iloc[10]

Id        561500
Name      Olivia
Year        2014
Gender         F
State         CA
Count       2407
Name: 561499, dtype: object

In [16]:
# Create a new DataFrame containing only California baby name records
ca_babies = state_babies.loc[state_babies['State'] == 'CA', :]

In [17]:
ca_babies

            Id      Name  Year Gender State  Count
356017  356018      Mary  1910      F    CA    295
356018  356019     Helen  1910      F    CA    239
356019  356020   Dorothy  1910      F    CA    220
356020  356021  Margaret  1910      F    CA    163
356021  356022   Frances  1910      F    CA    134
...        ...       ...   ...    ...   ...    ...
710225  710226    Zakary  2014      M    CA      5
710226  710227   Zealand  2014      M    CA      5
710227  710228      Ziad  2014      M    CA      5
710228  710229    Zidane  2014      M    CA      5
710229  710230     Ziyad  2014      M    CA      5

[354213 rows x 6 columns]

In [18]:
# Sort California baby names from highest Count to lowest Count
ca_babies_sorted = ca_babies.sort_values('Count', ascending=False)

In [19]:
# Define a function that returns the first name in each grouped list
# Since the data is already sorted by Count, the first name is the most popular
def popular(s):
    return s.iloc[0]

In [20]:
# Group California baby names by Year and Gender
# Then apply the popular function to find the most popular name in each group
ca_grouped = ca_babies_sorted.groupby(['Year', 'Gender']).agg(popular)

In [21]:
# Display the most popular female and male baby names in California for each year
ca_grouped

                 Id    Name State  Count
Year Gender
1910 F       356018    Mary    CA    295
     M       565480    John    CA    237
1911 F       356251    Mary    CA    390
     M       565610    John    CA    214
1912 F       356502    Mary    CA    534
...             ...     ...   ...    ...
2012 M       701517   Jacob    CA   2971
2013 F       557545  Sophia    CA   3451
     M       704421   Jacob    CA   2879
2014 F       561496  Sophia    CA   3162
     M       707312    Noah    CA   2761

[210 rows x 4 columns]