In [1]:
!pip install pandas

Requirement already satisfied: pandas in D:\Miniforge326.3.2-2\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in D:\Miniforge326.3.2-2\Lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in D:\Miniforge326.3.2-2\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in D:\Miniforge326.3.2-2\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in D:\Miniforge326.3.2-2\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd

In [3]:
import pandas as pd

print("Pandas works!")

Pandas works!

In [4]:
import os

os.getcwd()

'C:\\Users\\johnb'

In [5]:
import pandas as pd

data = pd.read_csv(r'D:\MiniForge\Ex_Files_Intro_to_Data_Science\Ex_Files_Intro_to_Data_Science\Exercise Files\us_baby_names.csv')

data.head()

   Id       Name  Year Gender  Count
0   1       Mary  1880      F   7065
1   2       Anna  1880      F   2604
2   3       Emma  1880      F   2003
3   4  Elizabeth  1880      F   1939
4   5     Minnie  1880      F   1746

In [6]:
data.head(10)
# shows first 10 rows

   Id       Name  Year Gender  Count
0   1       Mary  1880      F   7065
1   2       Anna  1880      F   2604
2   3       Emma  1880      F   2003
3   4  Elizabeth  1880      F   1939
4   5     Minnie  1880      F   1746
5   6   Margaret  1880      F   1578
6   7        Ida  1880      F   1472
7   8      Alice  1880      F   1414
8   9     Bertha  1880      F   1320
9  10      Sarah  1880      F   1288

In [7]:
data.tail()
#Shows Last 5 Rows

              Id     Name  Year Gender  Count
1825428  1825429   Zykeem  2014      M      5
1825429  1825430   Zymeer  2014      M      5
1825430  1825431  Zymiere  2014      M      5
1825431  1825432    Zyran  2014      M      5
1825432  1825433    Zyrin  2014      M      5

In [8]:
data.shape
# Show Number of Rows and Columns

(1825433, 5)

In [9]:
#Show Column Names
data.columns

Index(['Id', 'Name', 'Year', 'Gender', 'Count'], dtype='str')

In [10]:
# Show Column Names
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1825433 entries, 0 to 1825432
Data columns (total 5 columns):
 #   Column  Dtype
---  ------  -----
 0   Id      int64
 1   Name    str
 2   Year    int64
 3   Gender  str
 4   Count   int64
dtypes: int64(3), str(2)
memory usage: 69.6 MB

In [11]:
# basic Statistic
data.describe()

                 Id          Year         Count
count  1.825433e+06  1.825433e+06  1.825433e+06
mean   9.127170e+05  1.972620e+03  1.846879e+02
std    5.269573e+05  3.352891e+01  1.566711e+03
min    1.000000e+00  1.880000e+03  5.000000e+00
25%    4.563590e+05  1.949000e+03  7.000000e+00
50%    9.127170e+05  1.982000e+03  1.200000e+01
75%    1.369075e+06  2.001000e+03  3.200000e+01
max    1.825433e+06  2.014000e+03  9.968000e+04

In [12]:
# Find Most Popular Baby Names
data.sort_values(by='Count', ascending=False).head()

            Id     Name  Year Gender  Count
431052  431053    Linda  1947      F  99680
441424  441425    Linda  1948      F  96205
437157  437158    James  1947      M  94755
544602  544603  Michael  1957      M  92709
437158  437159   Robert  1947      M  91642

In [13]:
# Show Only Female Names
data[data['Gender'] == 'F'].head()

   Id       Name  Year Gender  Count
0   1       Mary  1880      F   7065
1   2       Anna  1880      F   2604
2   3       Emma  1880      F   2003
3   4  Elizabeth  1880      F   1939
4   5     Minnie  1880      F   1746

In [14]:
# Show Only Male Names
data[data['Gender'] == 'M'].head()

      Id     Name  Year Gender  Count
942  943     John  1880      M   9655
943  944  William  1880      M   9532
944  945    James  1880      M   5927
945  946  Charles  1880      M   5348
946  947   George  1880      M   5126

In [15]:
# Show First 20 Rows
data.head(100)

     Id       Name  Year Gender  Count
0     1       Mary  1880      F   7065
1     2       Anna  1880      F   2604
2     3       Emma  1880      F   2003
3     4  Elizabeth  1880      F   1939
4     5     Minnie  1880      F   1746
..  ...        ...   ...    ...    ...
95   96     Amelia  1880      F    221
96   97     Hannah  1880      F    221
97   98       Jane  1880      F    215
98   99   Virginia  1880      F    213
99  100      Emily  1880      F    210

[100 rows x 5 columns]

In [16]:
# Show Random Rows
data.sample(10)

              Id      Name  Year Gender  Count
1449468  1449469    Bilaal  2003      M      8
334189    334190   Verilea  1936      F      7
1047182  1047183      Elle  1989      F     96
801693    801694       Tim  1976      F      5
310577    310578      Hart  1933      M     10
78928      78929   Florina  1907      F      5
1710187  1710188   Mckenli  2011      F      5
1015131  1015132  Willisha  1987      F      5
167823    167824    Daryle  1919      M      8
404877    404878    Clydia  1944      F     24

In [17]:
import pandas as pd

us_babies = pd.read_csv(
    r'D:\MiniForge\Ex_Files_Intro_to_Data_Science\Ex_Files_Intro_to_Data_Science\Exercise Files\us_baby_names.csv'
)

us_babies.head()

   Id       Name  Year Gender  Count
0   1       Mary  1880      F   7065
1   2       Anna  1880      F   2604
2   3       Emma  1880      F   2003
3   4  Elizabeth  1880      F   1939
4   5     Minnie  1880      F   1746

In [18]:
us_babies['Year']

0          1880
1          1880
2          1880
3          1880
4          1880
           ...
1825428    2014
1825429    2014
1825430    2014
1825431    2014
1825432    2014
Name: Year, Length: 1825433, dtype: int64

In [19]:
us_babies['Year'] == 2014

0          False
1          False
2          False
3          False
4          False
           ...
1825428     True
1825429     True
1825430     True
1825431     True
1825432     True
Name: Year, Length: 1825433, dtype: bool

In [20]:
us_babies.loc[us_babies ['Year'] == 2014, : ]

              Id      Name  Year Gender  Count
1792389  1792390      Emma  2014      F  20799
1792390  1792391    Olivia  2014      F  19674
1792391  1792392    Sophia  2014      F  18490
1792392  1792393  Isabella  2014      F  16950
1792393  1792394       Ava  2014      F  15586
...          ...       ...   ...    ...    ...
1825428  1825429    Zykeem  2014      M      5
1825429  1825430    Zymeer  2014      M      5
1825430  1825431   Zymiere  2014      M      5
1825431  1825432     Zyran  2014      M      5
1825432  1825433     Zyrin  2014      M      5

[33044 rows x 5 columns]

In [21]:
us_babies_2014 = us_babies.loc[us_babies['Year'] == 2014, :]

In [22]:
us_babies_2014

              Id      Name  Year Gender  Count
1792389  1792390      Emma  2014      F  20799
1792390  1792391    Olivia  2014      F  19674
1792391  1792392    Sophia  2014      F  18490
1792392  1792393  Isabella  2014      F  16950
1792393  1792394       Ava  2014      F  15586
...          ...       ...   ...    ...    ...
1825428  1825429    Zykeem  2014      M      5
1825429  1825430    Zymeer  2014      M      5
1825430  1825431   Zymiere  2014      M      5
1825431  1825432     Zyran  2014      M      5
1825432  1825433     Zyrin  2014      M      5

[33044 rows x 5 columns]

In [23]:
us_babies_2014.sort_values('Count', ascending = False)

              Id     Name  Year Gender  Count
1792389  1792390     Emma  2014      F  20799
1792390  1792391   Olivia  2014      F  19674
1811456  1811457     Noah  2014      M  19144
1792391  1792392   Sophia  2014      F  18490
1811457  1811458     Liam  2014      M  18342
...          ...      ...   ...    ...    ...
1825424  1825425  Zmarion  2014      M      5
1825423  1825424   Ziyang  2014      M      5
1825422  1825423    Ziyah  2014      M      5
1825421  1825422    Zivon  2014      M      5
1825420  1825421    Zirui  2014      M      5

[33044 rows x 5 columns]